In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv('match.csv')

In [42]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [43]:
c = df.groupby('city')
c

In [44]:
len(c)

30

In [45]:
len(df)

636

In [46]:
df.size

11448

In [47]:
c.size

In [48]:
c.size()

city
Abu Dhabi          7
Ahmedabad         12
Bangalore         66
Bloemfontein       2
Cape Town          7
Centurion         12
Chandigarh        46
Chennai           48
Cuttack            7
Delhi             60
Dharamsala         9
Durban            15
East London        3
Hyderabad         49
Indore             5
Jaipur            33
Johannesburg       8
Kanpur             4
Kimberley          3
Kochi              5
Kolkata           61
Mumbai            85
Nagpur             3
Port Elizabeth     7
Pune              32
Raipur             6
Rajkot            10
Ranchi             7
Sharjah            6
Visakhapatnam     11
dtype: int64

In [49]:
c.size().sort_values(ascending=False)

city
Mumbai            85
Bangalore         66
Kolkata           61
Delhi             60
Hyderabad         49
Chennai           48
Chandigarh        46
Jaipur            33
Pune              32
Durban            15
Ahmedabad         12
Centurion         12
Visakhapatnam     11
Rajkot            10
Dharamsala         9
Johannesburg       8
Ranchi             7
Cuttack            7
Abu Dhabi          7
Port Elizabeth     7
Cape Town          7
Raipur             6
Sharjah            6
Kochi              5
Indore             5
Kanpur             4
Kimberley          3
East London        3
Nagpur             3
Bloemfontein       2
dtype: int64

In [50]:
c.first()

,id,season,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
city,,,,,,,,,,,,,,,,,
Abu Dhabi,458,2014,2014-04-16,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,41,0,JH Kallis,Sheikh Zayed Stadium,M Erasmus,RK Illingworth,NaN
Ahmedabad,180,2010,2010-03-15,Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,6,V Sehwag,"Sardar Patel Stadium, Motera",BG Jerling,RE Koertzen,NaN
Bangalore,5,2017,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN
Bloemfontein,161,2009,2009-05-15,Delhi Daredevils,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,B Lee,OUTsurance Oval,HDPK Dharmasena,IL Howell,NaN
Cape Town,118,2009,2009-04-18,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Mumbai Indians,19,0,SR Tendulkar,Newlands,BR Doctrove,K Hariharan,NaN
Centurion,133,2009,2009-04-28,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,bat,normal,0,Rajasthan Royals,0,5,YK Pathan,SuperSport Park,GAV Baxter,RE Koertzen,NaN
Chandigarh,32,2017,2017-04-28,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,26,0,Rashid Khan,"Punjab Cricket Association IS Bindra Stadium, ...",Nitin Menon,CK Nandan,NaN
Chennai,67,2008,2008-04-23,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,normal,0,Chennai Super Kings,6,0,ML Hayden,"MA Chidambaram Stadium, Chepauk",DJ Harper,GA Pratapkumar,NaN
Cuttack,186,2010,2010-03-19,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Deccan Chargers,6,0,A Symonds,Barabati Stadium,BF Bowden,M Erasmus,NaN
Delhi,15,2017,2017-04-15,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN
Dharamsala,225,2010,2010-04-16,Kings XI Punjab,Deccan Chargers,Deccan Chargers,field,normal,0,Deccan Chargers,0,5,RG Sharma,Himachal Pradesh Cricket Association Stadium,M Erasmus,AM Saheba,NaN
Durban,123,2009,2009-04-21,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,1,Kolkata Knight Riders,11,0,CH Gayle,Kingsmead,DJ Harper,SD Ranade,NaN
East London,138,2009,2009-05-01,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,bat,normal,0,Mumbai Indians,9,0,JP Duminy,Buffalo Park,M Erasmus,SK Tarapore,NaN
Hyderabad,1,2017,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
Indore,4,2017,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
Jaipur,65,2008,2008-04-21,Kings XI Punjab,Rajasthan Royals,Kings XI Punjab,bat,normal,0,Rajasthan Royals,0,6,SR Watson,Sawai Mansingh Stadium,Aleem Dar,RB Tiffin,NaN
Johannesburg,141,2009,2009-05-02,Chennai Super Kings,Delhi Daredevils,Delhi Daredevils,field,normal,0,Chennai Super Kings,18,0,SB Jakati,New Wanderers Stadium,DJ Harper,RE Koertzen,NaN
Kanpur,49,2017,2017-05-10,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,2,SS Iyer,Green Park,YC Barde,AK Chaudhary,NaN
Kimberley,151,2009,2009-05-09,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,3,DPMD Jayawardene,De Beers Diamond Oval,GAV Baxter,AM Saheba,NaN
Kochi,237,2011,2011-04-09,Kochi Tuskers Kerala,Royal Challengers Bangalore,Kochi Tuskers Kerala,bat,normal,0,Royal Challengers Bangalore,0,6,AB de Villiers,Nehru Stadium,HDPK Dharmasena,K Hariharan,NaN
Kolkata,11,2017,2017-04-13,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN
Mumbai,7,2017,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
Nagpur,210,2010,2010-04-05,Rajasthan Royals,Deccan Chargers,Rajasthan Royals,bat,normal,0,Rajasthan Royals,2,0,SK Warne,"Vidarbha Cricket Association Stadium, Jamtha",HDPK Dharmasena,SJA Taufel,NaN
Port Elizabeth,122,2009,2009-04-20,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,bat,normal,0,Chennai Super Kings,92,0,M Muralitharan,St George's Park,BG Jerling,SJA Taufel,NaN
Pune,2,2017,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
Raipur,419,2013,2013-04-28,Delhi Daredevils,Pune Warriors,Pune Warriors,field,normal,0,Delhi Daredevils,15,0,DA Warner,Shaheed Veer Narayan Singh International Stadium,CK Nandan,S Ravi,NaN
Rajkot,3,2017,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
Ranchi,441,2013,2013-05-12,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,5,JH Kallis,JSCA International Stadium Complex,NJ Llong,K Srinath,NaN
Sharjah,459,2014,2014-04-17,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,8,YS Chahal,Sharjah Cricket Stadium,Aleem Dar,S Ravi,NaN
Visakhapatnam,313,2012,2012-04-07,Chennai Super Kings,Deccan Chargers,Deccan Chargers,field,normal,0,Chennai Super Kings,74,0,RA Jadeja,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,JD Cloete,HDPK Dharmasena,NaN

In [51]:
c.last()

,id,season,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
city,,,,,,,,,,,,,,,,,
Abu Dhabi,476,2014,2014-04-29,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,tie,0,Rajasthan Royals,0,0,JP Faulkner,Sheikh Zayed Stadium,Aleem Dar,AK Chaudhary,NaN
Ahmedabad,540,2015,2015-04-24,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,MA Starc,"Sardar Patel Stadium, Motera",M Erasmus,S Ravi,NaN
Bangalore,636,2016,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
Bloemfontein,165,2009,2009-05-17,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,bat,normal,0,Delhi Daredevils,14,0,AB de Villiers,OUTsurance Oval,SS Hazare,IL Howell,NaN
Cape Town,130,2009,2009-04-26,Kings XI Punjab,Rajasthan Royals,Kings XI Punjab,bat,normal,0,Kings XI Punjab,27,0,KC Sangakkara,Newlands,M Erasmus,K Hariharan,NaN
Centurion,172,2009,2009-05-22,Delhi Daredevils,Deccan Chargers,Deccan Chargers,field,normal,0,Deccan Chargers,0,6,AC Gilchrist,SuperSport Park,BR Doctrove,DJ Harper,NaN
Chandigarh,622,2016,2016-05-15,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,bat,normal,0,Sunrisers Hyderabad,0,7,HM Amla,"Punjab Cricket Association IS Bindra Stadium, ...",KN Ananthapadmanabhan,M Erasmus,NaN
Chennai,563,2015,2015-05-10,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,bat,normal,0,Chennai Super Kings,12,0,RA Jadeja,"MA Chidambaram Stadium, Chepauk",M Erasmus,CK Nandan,NaN
Cuttack,497,2014,2014-05-14,Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,6,RV Uthappa,Barabati Stadium,AK Chaudhary,NJ Llong,NaN
Delhi,635,2016,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
Dharamsala,450,2013,2013-05-18,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,50,0,Azhar Mahmood,Himachal Pradesh Cricket Association Stadium,HDPK Dharmasena,CK Nandan,NaN
Durban,169,2009,2009-05-20,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,24,0,M Muralitharan,Kingsmead,BG Jerling,SJA Taufel,NaN
East London,150,2009,2009-05-08,Mumbai Indians,Delhi Daredevils,Mumbai Indians,bat,normal,0,Delhi Daredevils,0,7,A Nehra,Buffalo Park,M Erasmus,SK Tarapore,NaN
Hyderabad,618,2016,2016-05-12,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,7,CH Morris,"Rajiv Gandhi International Stadium, Uppal",K Bharatan,M Erasmus,NaN
Indore,294,2011,2011-05-15,Rajasthan Royals,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Kochi Tuskers Kerala,0,8,BJ Hodge,Holkar Cricket Stadium,PR Reiffel,RJ Tucker,NaN
Jaipur,442,2013,2013-05-12,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,5,SR Watson,Sawai Mansingh Stadium,HDPK Dharmasena,CK Nandan,NaN
Johannesburg,174,2009,2009-05-24,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Deccan Chargers,6,0,A Kumble,New Wanderers Stadium,RE Koertzen,SJA Taufel,NaN
Kanpur,630,2016,2016-05-21,Mumbai Indians,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,6,SK Raina,Green Park,AK Chaudhary,CK Nandan,NaN
Kimberley,155,2009,2009-05-11,Deccan Chargers,Rajasthan Royals,Deccan Chargers,bat,normal,0,Deccan Chargers,53,0,DR Smith,De Beers Diamond Oval,GAV Baxter,HDPK Dharmasena,NaN
Kochi,278,2011,2011-05-05,Kochi Tuskers Kerala,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kochi Tuskers Kerala,17,0,BJ Hodge,Nehru Stadium,S Ravi,RJ Tucker,NaN
Kolkata,631,2016,2016-05-22,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,22,0,YK Pathan,Eden Gardens,KN Ananthapadmanabhan,M Erasmus,NaN
Mumbai,600,2016,2016-04-28,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,RG Sharma,Wankhede Stadium,Nitin Menon,RJ Tucker,NaN
Nagpur,220,2010,2010-04-12,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Deccan Chargers,13,0,Harmeet Singh,"Vidarbha Cricket Association Stadium, Jamtha",RE Koertzen,RB Tiffin,NaN
Port Elizabeth,162,2009,2009-05-16,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Chennai Super Kings,0,7,ML Hayden,St George's Park,SK Tarapore,SJA Taufel,NaN
Pune,605,2016,2016-05-01,Rising Pune Supergiants,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,RG Sharma,Maharashtra Cricket Association Stadium,AY Dandekar,RJ Tucker,NaN
Raipur,632,2016,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
Rajkot,607,2016,2016-05-03,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,8,RR Pant,Saurashtra Cricket Association Stadium,CB Gaffaney,BNJ Oxenford,NaN
Ranchi,575,2015,2015-05-22,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,3,A Nehra,JSCA International Stadium Complex,AK Chaudhary,CB Gaffaney,NaN
Sharjah,474,2014,2014-04-27,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,normal,0,Chennai Super Kings,0,5,DR Smith,Sharjah Cricket Stadium,AK Chaudhary,VA Kulkarni,NaN
Visakhapatnam,629,2016,2016-05-21,Kings XI Punjab,Rising Pune Supergiants,Kings XI Punjab,bat,normal,0,Rising Pune Supergiants,0,4,MS Dhoni,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,HDPK Dharmasena,Nitin Menon,NaN

In [52]:
c.groups

{'Abu Dhabi': [457, 459, 460, 464, 470, 471, 475], 'Ahmedabad': [179, 186, 194, 197, 481, 486, 497, 500, 525, 532, 535, 539], 'Bangalore': [4, 11, 16, 29, 41, 44, 56, 57, 59, 69, 73, 83, 89, 103, 110, 180, 183, 191, 196, 213, 216, 225, 241, 267, 279, 282, 290, 301, 311, 316, 325, 328, 349, 355, 366, 378, 382, 391, 400, 406, 410, 428, 431, 451, 480, 487, 491, 494, 509, 516, 524, 533, 537, 545, 549, 556, 570, 579, 586, 605, 610, 616, 619, 625, 632, 635], 'Bloemfontein': [160, 164], 'Cape Town': [117, 118, 119, 120, 123, 125, 129], 'Centurion': [132, 135, 136, 146, 147, 148, 155, 156, 165, 169, 170, 171], 'Chandigarh': [31, 34, 45, 47, 60, 68, 72, 80, 93, 96, 107, 176, 192, 195, 204, 214, 242, 255, 283, 286, 320, 329, 332, 339, 353, 365, 390, 399, 408, 435, 439, 447, 504, 508, 511, 543, 551, 565, 568, 578, 585, 588, 596, 611, 614, 621], 'Chennai': [66, 70, 78, 84, 90, 106, 109, 178, 189, 201, 205, 210, 221, 223, 234, 247, 261, 271, 275, 288, 296, 305, 306, 307, 319, 331, 333, 342, 346, 351, 363, 379, 380, 385, 395, 398, 409, 413, 417, 424, 445, 518, 520, 541, 546, 553, 558, 562], 'Cuttack': [185, 188, 336, 347, 485, 490, 496], 'Delhi': [14, 17, 38, 40, 43, 50, 54, 61, 75, 86, 97, 99, 108, 182, 184, 199, 202, 208, 217, 228, 237, 252, 258, 262, 265, 273, 300, 317, 322, 334, 341, 344, 356, 368, 371, 384, 393, 403, 407, 437, 442, 453, 454, 479, 482, 484, 488, 501, 522, 534, 538, 542, 547, 582, 592, 598, 601, 608, 633, 634], 'Dharamsala': [224, 227, 292, 295, 299, 370, 373, 411, 449], 'Durban': [122, 124, 126, 127, 130, 133, 134, 138, 144, 145, 157, 158, 159, 167, 168], 'East London': [137, 143, 149], 'Hyderabad': [0, 5, 18, 20, 35, 42, 46, 58, 65, 67, 76, 79, 91, 101, 113, 235, 244, 248, 259, 274, 278, 285, 330, 358, 372, 375, 383, 387, 404, 422, 427, 434, 448, 452, 492, 495, 499, 502, 550, 563, 567, 571, 583, 587, 593, 597, 602, 609, 617], 'Indore': [3, 7, 21, 289, 293], 'Jaipur': [64, 77, 82, 88, 92, 100, 112, 211, 218, 222, 240, 245, 260, 266, 270, 284, 287, 310, 313, 327, 337, 348, 360, 364, 376, 388, 397, 402, 415, 419, 430, 432, 441], 'Johannesburg': [140, 142, 153, 162, 163, 166, 172, 173], 'Kanpur': [48, 51, 626, 629], 'Kimberley': [150, 151, 154], 'Kochi': [236, 251, 264, 268, 277], 'Kolkata': [10, 13, 22, 26, 30, 39, 52, 63, 74, 87, 94, 102, 104, 111, 177, 181, 203, 207, 212, 226, 229, 239, 250, 254, 257, 269, 280, 302, 308, 321, 324, 343, 352, 362, 367, 381, 396, 405, 412, 414, 426, 455, 456, 503, 505, 510, 513, 517, 521, 526, 544, 554, 559, 575, 577, 580, 607, 613, 620, 623, 630], 'Mumbai': [6, 9, 15, 23, 27, 36, 49, 55, 62, 71, 81, 85, 95, 98, 105, 114, 115, 116, 174, 175, 187, 190, 193, 198, 200, 206, 220, 230, 231, 232, 233, 238, 243, 246, 249, 253, 256, 263, 272, 276, 281, 291, 294, 297, 298, 303, 304, 309, 318, 326, 335, 345, 354, 359, 369, 389, 394, 416, 420, 429, 433, 443, 446, 478, 483, 489, 507, 512, 514, 515, 523, 529, 540, 548, 552, 555, 557, 561, 566, 569, 572, 576, 584, 589, 599], 'Nagpur': [209, 215, 219], 'Port Elizabeth': [121, 128, 131, 139, 141, 152, 161], 'Pune': [1, 8, 24, 28, 32, 37, 53, 314, 323, 338, 340, 350, 357, 361, 374, 377, 386, 392, 401, 421, 425, 436, 438, 450, 519, 527, 531, 573, 591, 595, 600, 604], 'Raipur': [418, 423, 560, 564, 627, 631], 'Rajkot': [2, 12, 19, 25, 33, 581, 590, 594, 603, 606], 'Ranchi': [440, 444, 477, 493, 498, 506, 574], 'Sharjah': [458, 463, 465, 467, 472, 473], 'Visakhapatnam': [312, 315, 528, 530, 536, 612, 615, 618, 622, 624, 628]}

In [53]:
df.iloc[48:]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
48,49,2017,Kanpur,2017-05-10,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,2,SS Iyer,Green Park,YC Barde,AK Chaudhary,NaN
49,50,2017,Mumbai,2017-05-11,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,7,0,WP Saha,Wankhede Stadium,A Deshmukh,A Nand Kishore,NaN
50,51,2017,Delhi,2017-05-12,Delhi Daredevils,Rising Pune Supergiant,Delhi Daredevils,bat,normal,0,Delhi Daredevils,7,0,KK Nair,Feroz Shah Kotla,KN Ananthapadmanabhan,CK Nandan,NaN
51,52,2017,Kanpur,2017-05-13,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,8,Mohammed Siraj,Green Park,AK Chaudhary,Nitin Menon,NaN
52,53,2017,Kolkata,2017-05-13,Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Mumbai Indians,9,0,AT Rayudu,Eden Gardens,A Nand Kishore,S Ravi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [54]:
c.get_group('Kanpur')

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
48,49,2017,Kanpur,2017-05-10,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,2,SS Iyer,Green Park,YC Barde,AK Chaudhary,NaN
51,52,2017,Kanpur,2017-05-13,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,8,Mohammed Siraj,Green Park,AK Chaudhary,Nitin Menon,NaN
626,627,2016,Kanpur,2016-05-19,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,6,DR Smith,Green Park,AK Chaudhary,CK Nandan,NaN
629,630,2016,Kanpur,2016-05-21,Mumbai Indians,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,6,SK Raina,Green Park,AK Chaudhary,CK Nandan,NaN

In [55]:
c.get_group('Kanpur').shape

(4, 18)

In [56]:
c.sum()

,id,season,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
city,,,,,,,,,,,,,,,,,
Abu Dhabi,3263,14098,2014-04-162014-04-182014-04-182014-04-212014-0...,Kolkata Knight RidersChennai Super KingsSunris...,Mumbai IndiansKings XI PunjabRajasthan RoyalsD...,Kolkata Knight RidersChennai Super KingsRajast...,batbatfieldbatfieldfieldbat,normalnormalnormalnormalnormalnormaltie,0,Kolkata Knight RidersKings XI PunjabRajasthan ...,157,16,JH KallisGJ MaxwellAM RahaneSK RainaPV TambeSa...,Sheikh Zayed StadiumSheikh Zayed StadiumSheikh...,M ErasmusRK IllingworthBF BowdenRK Illingworth...,RK IllingworthC ShamshuddinRK IllingworthC Sha...,0.0
Ahmedabad,4863,24156,2010-03-152010-03-202010-03-262010-03-282014-0...,Rajasthan RoyalsRajasthan RoyalsDeccan Charger...,Delhi DaredevilsKolkata Knight RidersRajasthan...,Delhi DaredevilsRajasthan RoyalsDeccan Charger...,fieldbatbatbatfieldfieldfieldbatbatbatfieldfield,normalnormalnormalnormalnormalnormalnormalnorm...,0,Delhi DaredevilsRajasthan RoyalsRajasthan Roya...,180,38,V SehwagAA JhunjhunwalaYK PathanNV OjhaPV Tamb...,"Sardar Patel Stadium, MoteraSardar Patel Stadi...",BG JerlingRE KoertzenHDPK DharmasenaSS HazareN...,RE KoertzenRB TiffinSJA TaufelSJA TaufelCK Nan...,0.0
Bangalore,22299,132861,2017-04-082017-04-142017-04-162017-04-272017-0...,Royal Challengers BangaloreRoyal Challengers B...,Delhi DaredevilsMumbai IndiansRoyal Challenger...,Royal Challengers BangaloreMumbai IndiansRoyal...,batfieldfieldfieldfieldfieldfieldfieldfieldfie...,normalnormalnormalnormalnormalnormalnormalnorm...,3,Royal Challengers BangaloreMumbai IndiansRisin...,1263,232,KM JadhavKA PollardBA StokesAJ TyeSandeep Shar...,M Chinnaswamy StadiumM Chinnaswamy StadiumM Ch...,KN AnanthapadmanabhanKN AnanthapadmanabhanAK C...,AK ChaudharyC ShamshuddinC ShamshuddinC Shamsh...,0.0
Bloemfontein,326,4018,2009-05-152009-05-17,Delhi DaredevilsDelhi Daredevils,Kings XI PunjabRajasthan Royals,Kings XI PunjabDelhi Daredevils,fieldbat,normalnormal,0,Kings XI PunjabDelhi Daredevils,14,6,B LeeAB de Villiers,OUTsurance OvalOUTsurance Oval,HDPK DharmasenaSS Hazare,IL HowellIL Howell,0.0
Cape Town,858,14063,2009-04-182009-04-182009-04-192009-04-192009-0...,Mumbai IndiansRoyal Challengers BangaloreKings...,Chennai Super KingsRajasthan RoyalsDelhi Dared...,Chennai Super KingsRoyal Challengers Bangalore...,fieldbatfieldbatbatfieldbat,normalnormalnormalnormalnormaltienormal,1,Mumbai IndiansRoyal Challengers BangaloreDelhi...,145,18,SR TendulkarR DravidDL VettoriRP SinghAC Gilch...,NewlandsNewlandsNewlandsNewlandsNewlandsNewlan...,BR DoctroveBR DoctroveMR BensonMR BensonM Eras...,K HariharanRB TiffinSD RanadeBR DoctroveAM Sah...,0.0
Centurion,1842,24108,2009-04-282009-04-302009-04-302009-05-062009-0...,Delhi DaredevilsDeccan ChargersChennai Super K...,Rajasthan RoyalsDelhi DaredevilsRajasthan Roya...,Delhi DaredevilsDelhi DaredevilsRajasthan Roya...,batfieldfieldbatfieldbatfieldbatbatfieldbatfield,normalnormalnormalnormalnormalnormalnormalnorm...,1,Rajasthan RoyalsDelhi DaredevilsChennai Super ...,81,49,YK PathanDP NannesSK RainaRG SharmaA SinghML H...,SuperSport ParkSuperSport ParkSuperSport ParkS...,GAV BaxterGAV BaxterGAV BaxterMR BensonK Harih...,RE KoertzenAM SahebaRE KoertzenHDPK Dharmasena...,0.0
Chandigarh,15325,92582,2017-04-282017-04-302017-05-072017-05-092008-0...,Sunrisers HyderabadDelhi DaredevilsKings XI Pu...,Kings XI PunjabKings XI PunjabGujarat LionsKol...,Kings XI PunjabKings XI PunjabGujarat LionsKol...,fieldfieldfieldfieldbatfieldbatbatbatfieldfiel...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Sunrisers HyderabadKings XI PunjabGujarat Lion...,576,167,Rashid KhanSandeep SharmaDR SmithMM SharmaMEK ...,"Punjab Cricket Association IS Bindra Stadium, ...",Nitin MenonYC BardeA Nand KishoreA Nand Kishor...,CK NandanCK NandanVK SharmaS RaviSL ShastriAM ...,0.0
Chennai,15096,96554,2008-04-232008-04-262008-05-022008-05-062008-0...,Chennai Super KingsKolkata Knight RidersChenna...,Mumbai IndiansChennai Super KingsDelhi Daredev...,Mumbai IndiansKolkata Knight RidersChennai Sup...,fieldbatbatfieldfieldbatbatbatfieldbatbatbatba...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Chennai Super KingsChennai Super KingsDelhi Da...,715,111,ML HaydenJDP OramV SehwagAC GilchristL BalajiA...,"MA Chidambaram Stadium, ChepaukMA Chidambaram ...",DJ HarperBF BowdenBF BowdenMR BensonAV Jayapra...,GA PratapkumarAV JayaprakashK HariharanRB Tiff...,0.0
Cuttack,2534,14086,2010-03-192010-03-212012-04-222012-05-012014-0...,Deccan ChargersDeccan ChargersDeccan ChargersD...,Kings XI PunjabDelhi DaredevilsKolkata Knight ...,Kings XI PunjabDeccan ChargersKolkata Knight R...,fieldbatfieldbatfieldfieldfield,normalnormalnormalnormalnormalnormalnormal,0,Deccan ChargersDeccan ChargersKolkata Knight R...,73,20,A SymondsA SymondsB LeeKC SangakkaraGJ Maxwell...,Barabati StadiumBarabati StadiumBarabati Stadi...,BF BowdenBF BowdenBF BowdenAleem DarHDPK Dharm...,M ErasmusM ErasmusSK TaraporeAK ChaudharyPG Pa...,0.0
Delhi,19600,120771,2017-04-152017-04-172017-05-022017-05-042017-0...,Delhi DaredevilsDelhi DaredevilsSunrisers Hyde...,Kings XI PunjabKolkata Knight RidersDelhi Dare...,Delhi DaredevilsDelhi DaredevilsDelhi Daredevi...,batbatfieldfieldfieldbatbatbatfieldfieldfieldb...,normalnormalnormalnormalnormalnormalnormalnorm...,2,Delhi DaredevilsKolkata Knight RidersDelhi Dar...,876,192,CJ AndersonNM Coulter-NileMohammed ShamiRR Pan...,Feroz Shah KotlaFeroz Shah KotlaFeroz Shah Kot...,YC BardeNitin MenonYC BardeM ErasmusNitin Meno...,Nitin MenonCK NandanNitin MenonNitin MenonCK N...,0.0
Dharamsala,2949,18103,2010-04-162010-04-182011-05-152011-05-172011-0...,Kings XI PunjabKings XI PunjabKings XI PunjabK...,Deccan ChargersChennai Super KingsDelhi Darede...,Deccan ChargersChennai Super KingsDelhi Darede...,fieldfieldfieldbatfieldfieldfieldfieldfield,normalnormalnormalnormalnormalnormalnormalnorm...,0,Deccan ChargersChennai Super KingsKings XI Pun...,279,23,RG SharmaMS DhoniPP ChawlaAC GilchristS Dhawan...,Himachal Pradesh Cricket Association StadiumHi...,M ErasmusBF BowdenAsad RaufAsad RaufAsad RaufV...,AM SahebaAM SahebaSL ShastriAM SahebaAM Saheba...,0.0
Durban,2147,30135,2009-04-212009-04-232009-04-242009-04-252009-0...,Kings XI PunjabDelhi DaredevilsRoyal Challenge...,Kolkata Knight RidersChennai Super KingsKings ...,Kolkata Knight RidersDelhi DaredevilsRoyal Cha...,fieldbatbatbatfieldbatbatbatfieldbatfieldbatba...,normalnormalnormalnormalnormalnormalnormalnorm...,1,Kolkata Knight RidersDelhi DaredevilsKings XI ...,159,33,CH GayleAB de VilliersRS BoparaPP OjhaHH Gibbs...,KingsmeadKingsmeadKingsmeadKingsmeadKingsmeadK...,DJ HarperBR DoctroveBR DoctroveHDPK Dharmasena...,SD RanadeSJA TaufelTH WijewardeneSJA TaufelTH ...,0.0
East London,432,6027,2009-05-012009-05-042009-05-08,Mumbai IndiansChennai Super KingsMumbai Indians,Kolkata Knight RidersDeccan ChargersDelhi Dare...,Mumbai IndiansChennai Super KingsMumbai Indians,batbatbat,normalnormalnormal,0,Mumbai IndiansChennai Super KingsDelhi Daredevils,87,7,JP DuminyMS DhoniA Nehra,Buffalo ParkBuffalo ParkBuffalo Park,M ErasmusBR DoctroveM Erasmus,SK TaraporeM ErasmusSK Tarapore,0.0
Hyderabad,15907,98649,2017-04-052017-04-092017-04-172017-04-192017-0...,Sunrisers HyderabadGujarat LionsSunrisers Hyde...,Royal Challengers BangaloreSunrisers Hyderabad...,Royal Challengers BangaloreSunrisers Hyderabad...,fieldfieldfieldbatfieldfieldbatbatbatfieldfiel...,normalnormalnormalnormalnormalnormalnormalnorm...,2,Sunrisers HyderabadSunrisers HyderabadSunriser...,486,184,Yuvraj SinghRashid KhanB KumarKS WilliamsonDA ...,"Rajiv Gandhi International Stadium, UppalRajiv...",AY DandekarA DeshmukhAY DandekarCB GaffaneyAY ...,NJ LlongNJ LlongA DeshmukhNJ LlongS RaviAK Cha...,0.0
Indore,618,10073,2017-04-082017-04-102017-04-202011-05-132011-0...,Rising Pune SupergiantRoyal Challengers Bangal...,Kings XI PunjabKings XI PunjabMumbai IndiansKi...,Kings XI PunjabRoyal Challengers BangaloreMumb...,fieldbatfieldfieldfield,normalnormalnormalnormalnormal,0,Kings XI PunjabKings XI PunjabMumbai IndiansKi...,0,36,GJ MaxwellAR PatelJC ButtlerKD KarthikBJ Hodge,Holkar Cricket StadiumHolkar Cricket StadiumHo...,AK ChaudharyAK ChaudharyM ErasmusS AsnaniPR Re...,C ShamshuddinC ShamshuddinC ShamshuddinRJ Tuck...,0.0
Jaipur,9210,66363,2008-04-212008-05-012008-05-042008-05-092008-0...,Kings XI PunjabRajasthan RoyalsChennai Super K...,Rajasthan RoyalsKolkata Knight RidersRajasthan...,Kings XI PunjabRajasthan RoyalsChennai Super K...,batbatbatfieldfieldfieldfieldbatfieldbatbatfie...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Rajasthan RoyalsRajasthan RoyalsRajasthan Roya...,460,151,SR WatsonSA AsnodkarSohail TanvirYK PathanSR W...,Sawai Mansingh StadiumSawai Mansingh StadiumSa...,Aleem DarRE KoertzenAsad RaufMR BensonSJ Davis...,RB TiffinGA PratapkumarAV JayaprakashAM Saheba...,0.0
Johannesburg,1279,16072,2009-05-022009-05-032009-05-102009-05-162009-0...,Chennai Super KingsMumbai IndiansKolkata Knigh...,Delhi DaredevilsRoyal Challengers BangaloreDel...,Delhi DaredevilsMumbai IndiansDelhi Daredevils...,fieldbatfieldfieldfieldbatfieldfield,normalnormalnormalnormalnormalnormalnormalnormal,0,Chennai Super KingsRoyal Challengers Bangalore...,25,35,SB JakatiJH KallisA MishraRG SharmaYuvraj Sing...,New Wanderers StadiumNew Wanderers StadiumNew ...,DJ HarperRE KoertzenSL ShastriRE KoertzenS Rav...,RE KoertzenTH WijewardeneRB TiffinS RaviRB Tif...,0.0
Kanpur,1358,8066,2017-05-102017-05-132016-05-192016-05-21,Gujarat LionsGujarat LionsKolkata Knight Rider...,Delhi DaredevilsSunrisers HyderabadGujarat Lio...,Delhi DaredevilsSunrisers HyderabadGujarat Lio...,fieldfieldfieldfield,normalnormalnormalnormal,0,Delhi DaredevilsSunrisers HyderabadGujarat Lio...,0,22,SS IyerMohammed SirajDR SmithSK Raina,Green ParkGreen ParkGreen ParkGreen Park,YC BardeAK ChaudharyAK ChaudharyAK Chaudhary,AK ChaudharyNitin MenonCK NandanCK Nandan,0.0
Kimberley,458,6027,2009-05-092009-05-092009-05-11,Deccan ChargersRajasthan RoyalsDeccan Chargers,Kings XI PunjabChennai Super KingsRajasthan Ro...,Kings XI PunjabRajasthan RoyalsDeccan Chargers,fieldbatbat,normalnormalnormal,0,Kings XI PunjabChennai Super KingsDeccan Chargers,53,10,DPMD JayawardeneS BadrinathDR Smith,De Beers Diamond OvalDe Beers Diamond OvalDe B...,GAV BaxterGAV BaxterGAV Baxter,AM SahebaHDPK DharmasenaHDPK Dharmasena,0.0
Kochi,1301,10055,2011-04-092011-04-182011-04-272011-04-302011-0...,Kochi Tuskers KeralaChennai Super KingsDeccan ...,Royal Challengers BangaloreKochi Tuskers Keral...,Kochi Tuskers KeralaKochi Tuskers KeralaKochi ...,batfieldfieldbatfield,normalnormalnormalnormalnormal,1,Royal Challengers BangaloreKochi Tuskers Keral...,110,13,AB de VilliersBB McCullumI SharmaV SehwagBJ Hodge,Nehru StadiumNehru StadiumNehru StadiumNehru S...,HDPK DharmasenaK HariharanHDPK DharmasenaHDPK ...,K HariharanAL HillAL HillAL HillRJ Tucker,0.0
Kolkata,19973,122783,2017-04-132017-04-152017-04-212017-04-232017-0...,Kings XI PunjabKolkata Knight RidersKolkata Kn...,Kolkata Knight RidersSunrisers HyderabadGujara...,Kolkata Knight RidersSunrisers HyderabadGujara...,fieldfieldfieldfieldfieldfieldfieldbatbatbatba...,normalnormalnormalnormalnormalnormalnormalnorm...,3,Kolkata Knight RidersKolkata Knight RidersGuja...,587,224,SP NarineRV UthappaSK RainaNM Coulter-NileG Ga...,Eden GardensEden GardensEden GardensEden Garde...,A DeshmukhAY DandekarCB GaffaneyCB GaffaneyNJ ...,NJ LlongNJ LlongNitin MenonCK NandanS RaviA Na...,0.0
Mumbai,26283,171049,2017-04-092017-04-122017-04-162017-04-222017-0...,Kolkata Knight RidersSunrisers HyderabadGujara...,Mumbai IndiansMumbai IndiansMumbai IndiansDelh...,Mumbai IndiansMumbai IndiansMumbai IndiansDelh...,fieldfieldfieldfieldfieldbatfieldfieldbatfield...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Mumbai IndiansMumbai IndiansMumbai IndiansMumb...,1102,264,N RanaJJ BumrahN RanaMJ McClenaghanBA StokesRG...,Wankhede StadiumWankhede StadiumWankhede Stadi...,Nitin MenonNitin MenonA Nand KishoreA Nand Kis...,CK NandanCK NandanS RaviS RaviS RaviCB Gaffane...,0.0
Nagpur,646,6030,2010-04-052010-04-102010-04-12,Rajasthan RoyalsChennai Super KingsDeccan Char...,Deccan ChargersDeccan ChargersRoyal Challenger...,Rajasthan RoyalsChennai Super KingsRoyal Chall...,batbatfield,normalnormalnormal,0,Rajasthan RoyalsDeccan ChargersDeccan Chargers,15,6,SK WarneRJ HarrisHarmeet Singh,"Vidarbha Cricket Association Stadium, JamthaVi...",HDPK DharmasenaHDPK DharmasenaRE Koertzen,SJA TaufelSJA TaufelRB Tiffin,0.0
Port Elizabeth,980,14063,2009-04-202009-04-262009-04-272009-05-022009-0...,Chennai Super KingsRoyal Challengers Bangalore...,Royal Challengers BangaloreDelhi DaredevilsKol...,Chennai Super KingsRoyal Challengers Bangalore...,batbatbatbatbatbatbat,normalnormalnormalnormalnormalnormalnormal,0,Chennai Super KingsDelhi DaredevilsMumbai Indi...,200,22,M MuralitharanTM DilshanSR TendulkarYK PathanD...,St George's ParkSt George's ParkSt George's Pa...,BG JerlingS AsnaniBG JerlingS AsnaniS AsnaniBR...,SJA TaufelBG JerlingRB TiffinBG JerlingMR Bens...,0.0
Pune,11238,64455,2017-04-062017-04-112017-04-222017-04-262017-0...,Mumbai IndiansDelhi DaredevilsSunrisers Hydera...,Rising Pune SupergiantRising Pune SupergiantRi...,Rising Pune SupergiantRising Pune SupergiantRi...,fieldfieldfieldfieldfieldfieldfieldbatbatbatba...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Rising Pune SupergiantDelhi DaredevilsRising P...,545,98,SPD SmithSV SamsonMS DhoniRV UthappaLH Ferguso...,Maharashtra Cricket Association StadiumMaharas...,A Nand KishoreAY DandekarAY DandekarAY Dandeka...,S RaviS RaviA DeshmukhNJ LlongM ErasmusC Shams...,0.0
Raipur,3229,12088,2013-04-282013-05-012015-05-092015-05-122016-0...,Delhi DaredevilsKolkata Knight RidersSunrisers...,Pune WarriorsDelhi DaredevilsDelhi DaredevilsD...,Pune WarriorsKolkata Knight RidersSunrisers Hy...,fieldbatbatbatfieldfield,normalnormalnormalnormalnormalnormal,0,Delhi DaredevilsDelhi DaredevilsSunrisers Hyde...,21,25,DA WarnerDA WarnerMC HenriquesZ KhanKK NairV K...,Shaheed Veer Narayan Singh International Stadi...,CK NandanHDPK DharmasenaVA KulkarniRK Illingwo...,S RaviCK NandanS RaviVA KulkarniBNJ OxenfordBN...,0.0
Rajkot,3075,20165,2017-04-072017-04-142017-04-182017-04-232017-0...,Gujarat LionsRising Pune SupergiantRoyal Chall...,Kolkata Knight RidersGujarat LionsGujarat Lion...,Kolkata Knight RidersGujarat LionsGujarat Lion...,fieldfieldfieldfieldbatbatfieldbatfieldfield,normalnormalnormalnormaltienormalnormalnormaln...,0,Kolkata Knight RidersGujarat LionsRoyal Challe...,70,48,CA LynnAJ TyeCH GayleHM AmlaKH PandyaAJ FinchB...,Saurashtra Cricket Association StadiumSaurasht...,Nitin MenonA Nand KishoreS RaviAK ChaudharyAK ...,CK NandanS RaviVK SharmaM ErasmusCB GaffaneyCK...,0.0
Ranchi,3439,14097,2013-05-122013-05-152014-05-022014-05-132014-0...,Royal Challengers BangalorePune WarriorsChenna...,Kolkata Knight RidersKolkata Knight RidersKolk...,Kolkata Knight RidersKolkata Knight RidersChen...,fieldfieldbatbatbatfieldfield,normalnormalnormalnormalnormalnormalnormal,0,Kolkata Knight RidersPune WarriorsChennai Supe...,41,24,JH KallisMK PandeyRA JadejaRA JadejaAB de Vill...,JSCA International Stadium ComplexJSCA Interna...,NJ LlongNJ LlongAK ChaudharyBNJ OxenfordBNJ Ox...,K SrinathK SrinathNJ LlongC ShamshuddinC Shams...,0.0
Sharjah,2804,12084,2014-04-172014-04-202014-04-222014-04-242014-0...,Delhi DaredevilsRajasthan RoyalsKings XI Punja...,Royal Challengers BangaloreKings XI PunjabSunr...,Royal Challengers BangaloreKings XI PunjabSunr...,fieldfieldfieldfieldbatbat,normalnormalnormalnormalnormalnormal,0,Royal Challengers BangaloreKings XI PunjabKing...,74,26,YS ChahalGJ MaxwellGJ MaxwellCA LynnM VijayDR ...,Sharjah Cricket StadiumSharjah Cricket Stadium...,Aleem DarBF BowdenM ErasmusAleem DarAleem DarA...,S RaviM ErasmusS RaviVA KulkarniVA KulkarniVA ...,0.0
Visakhapatnam,5951,22165,2012-04-072012-04-092015-04-162015-04-182015-0...,Chennai Super KingsDeccan ChargersSunrisers Hy...,Deccan ChargersMumbai IndiansRajasthan RoyalsS...,Deccan ChargersDeccan ChargersRajasthan Royals...,fieldbatfieldbatfieldfieldbatbatfieldfieldbat,normalnormalnormalnormalnormalnormalnormalnorm...,2,Chennai Super KingsMumbai IndiansRajasthan Roy...,282,22,RA JadejaRG SharmaAM RahaneJP DuminyDA WarnerA...,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,JD CloeteAK ChaudharyPG PathakPG PathakRK Illi...,HDPK DharmasenaJD CloeteS RaviS RaviVA Kulkarn...,0.0

In [58]:
c['win_by_wickets'].mean()

city
Abu Dhabi         2.285714
Ahmedabad         3.166667
Bangalore         3.515152
Bloemfontein      3.000000
Cape Town         2.571429
Centurion         4.083333
Chandigarh        3.630435
Chennai           2.312500
Cuttack           2.857143
Delhi             3.200000
Dharamsala        2.555556
Durban            2.200000
East London       2.333333
Hyderabad         3.755102
Indore            7.200000
Jaipur            4.575758
Johannesburg      4.375000
Kanpur            5.500000
Kimberley         3.333333
Kochi             2.600000
Kolkata           3.672131
Mumbai            3.105882
Nagpur            2.000000
Port Elizabeth    3.142857
Pune              3.062500
Raipur            4.166667
Rajkot            4.800000
Ranchi            3.428571
Sharjah           4.333333
Visakhapatnam     2.000000
Name: win_by_wickets, dtype: float64

In [59]:
c['win_by_wickets'].mean().sort_values()

city
Visakhapatnam     2.000000
Nagpur            2.000000
Durban            2.200000
Abu Dhabi         2.285714
Chennai           2.312500
East London       2.333333
Dharamsala        2.555556
Cape Town         2.571429
Kochi             2.600000
Cuttack           2.857143
Bloemfontein      3.000000
Pune              3.062500
Mumbai            3.105882
Port Elizabeth    3.142857
Ahmedabad         3.166667
Delhi             3.200000
Kimberley         3.333333
Ranchi            3.428571
Bangalore         3.515152
Chandigarh        3.630435
Kolkata           3.672131
Hyderabad         3.755102
Centurion         4.083333
Raipur            4.166667
Sharjah           4.333333
Johannesburg      4.375000
Jaipur            4.575758
Rajkot            4.800000
Kanpur            5.500000
Indore            7.200000
Name: win_by_wickets, dtype: float64

In [60]:
df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [62]:
c = df.groupby('player_of_match')
c

In [ ]:
N